# Generated by Django 6.1 on 2026-08-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='health_tools/')),
                ('short_description', models.CharField(max_length=250)),
                ('detailed_content', models.TextField()),
                ('category', models.CharField(choices=[('monitoring', 'Health Monitoring Device'), ('telemedicine', 'Telemedicine'), ('mobile_app', 'Mobile Application'), ('emergency', 'Emergency Information')], max_length=30)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PreventiveHealthTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(choices=[('ncd', 'Non-Communicable Diseases'), ('communicable', 'Communicable Diseases'), ('maternal_child', 'Maternal & Child Health'), ('mental', 'Mental Wellbeing')], max_length=30)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='preventive_health/')),
                ('summary', models.CharField(max_length=300)),
                ('detailed_content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
