# Generated by Django 6.1 on 2026-08-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(choices=[('campaign_news', 'Campaign News'), ('announcements', 'Announcements'), ('upcoming_events', 'Upcoming Events'), ('health_awareness', 'Health Awareness'), ('program_updates', 'Program Updates')], max_length=30)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('summary', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, max_length=120)),
                ('published_date', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
