# Generated by Django 6.1 on 2026-08-18 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('province', models.CharField(choices=[('koshi', 'Koshi'), ('madhesh', 'Madhesh'), ('bagmati', 'Bagmati'), ('gandaki', 'Gandaki'), ('lumbini', 'Lumbini'), ('karnali', 'Karnali'), ('sudurpashchim', 'Sudurpashchim')], max_length=30)),
                ('geographic_region', models.CharField(blank=True, help_text='e.g. Karnali hills, Mid-western Nepal', max_length=100)),
                ('description', models.TextField()),
                ('estimated_population', models.PositiveIntegerField(blank=True, null=True)),
                ('healthcare_situation', models.TextField(blank=True)),
                ('internet_mobile_situation', models.TextField(blank=True)),
                ('major_health_challenges', models.TextField(blank=True)),
                ('digital_health_needs', models.TextField(blank=True)),
                ('campaign_activities_summary', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='campaign_areas/')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('map_x', models.FloatField(blank=True, help_text='X position (0-100) on the districts overview', null=True)),
                ('map_y', models.FloatField(blank=True, help_text='Y position (0-100) on the districts overview', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign Area',
                'verbose_name_plural': 'Campaign Areas',
                'ordering': ['district_name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAreaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaign_areas/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='campaigns.campaignarea')),
            ],
        ),
    ]
