# Generated by Django 6.1 on 2026-08-18 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='resources/thumbnails/')),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('poster', 'Poster'), ('infographic', 'Infographic'), ('pdf', 'PDF')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('content', models.TextField(blank=True, help_text='Full article body, for type=article')),
                ('file', models.FileField(blank=True, help_text='For PDF, poster, or infographic types', null=True, upload_to='resources/files/')),
                ('external_video_url', models.URLField(blank=True, help_text='For type=video (e.g. YouTube link)')),
                ('author', models.CharField(blank=True, max_length=120)),
                ('published_date', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.resourcecategory')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
