# Generated by Django 6.1 on 2026-08-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='Digital Health Awareness Campaign', max_length=200)),
                ('slogan', models.CharField(default='Digital Knowledge for a Healthier Nepal', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_description', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('introduction', models.TextField(blank=True)),
                ('contact_address', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('stat_districts', models.PositiveIntegerField(default=0)),
                ('stat_people_reached', models.PositiveIntegerField(default=0)),
                ('stat_programs', models.PositiveIntegerField(default=0)),
                ('stat_volunteers', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign Settings',
                'verbose_name_plural': 'Campaign Settings',
            },
        ),
    ]
