# Generated by Django 6.1 on 2026-08-18 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Team Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('position', models.CharField(max_length=150)),
                ('district_location', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('experience', models.TextField(blank=True)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated', max_length=300)),
                ('responsibilities', models.TextField(blank=True)),
                ('biography', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='team.teamcategory')),
            ],
            options={
                'ordering': ['display_order', 'full_name'],
            },
        ),
    ]
