# Generated by Django 6.1 on 2026-08-18 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(choices=[('campaign_activities', 'Campaign Activities'), ('community_programs', 'Community Programs'), ('training_programs', 'Training Programs'), ('field_visits', 'Field Visits'), ('awareness_videos', 'Awareness Videos'), ('campaign_videos', 'Campaign Videos'), ('training_videos', 'Training Videos'), ('interviews', 'Interviews')], max_length=30)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/covers/')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/media/')),
                ('video_url', models.URLField(blank=True, help_text='Embedded video URL (YouTube etc.), for media_type=video')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='gallery.galleryalbum')),
            ],
        ),
    ]
